### ISSUE TITLE
程序语言设计导论的 Const 形式化描述的小纠错

### ISSUE THREAD

**Issue by HYDlink** [Yescafe/Yescafe.github.io#46]
https://github.com/Yescafe/Yescafe.github.io/blob/677cbb0dde89cd6c942d259c8ac597a504895e4e/_posts/2022-10-24-pl-theory-and-implementation.md?plain=1#L136

Const push down fomula missing $i$

should be

```latex
\frac{}{\operatorname{Cst}(i) \Downarrow i } \operatorname{E-const}
```

**Comment by Yescafe** [comment]
Thanks, fixed.
